### ISSUE TITLE
Deterministic calculation of k value in ECDSA implementation

### ISSUE THREAD

**Issue by matejr** [ripple/ripple-dot-net#11]
This implementation uses deterministic calculator for k value based on RFC 6979. However, other Ripple signers seem to use non-deterministic ECDSA variant.

Is this ok/intentional?

**Comment by sublimator** [comment]
It's intentional that this uses rfc6979. ripple-lib javascript now does
also, via use of the elliptic library. On the verification end, nothing
special needs to be done. rippled I believe will move in that direction
also, once openssl is fuy replaced by the secp256k1 library spearheaded by
the bitcoin folk.
