### ISSUE TITLE
Publish roadmap document

### ISSUE THREAD

**Issue by matejr** [ripple/ripple-dot-net#12]
Can you please create a roadmap? 

I'd like to find out whether it makes sense to add some of my Ripple related .NET code into this repository.

**Comment by sublimator** [comment]
What sort of code? :)

**Comment by matejr** [comment]
I have different code hanging around. For example, incomplete Rippled RPC client, REST client, transaction builders (similar to prepare* methods in RippleAPI) which create strongly-typed unsigned transaction objects etc. I don't know if these things are outside the scope of this project because it looks quite low level.

**Comment by sublimator** [comment]
Will get back to you :) Merry Xmas

**Comment by matejr** [comment]
Merry Xmas to you, too!

**Comment by sublimator** [comment]
> create strongly-typed unsigned transaction objects etc

Do you have any links? Would love to take a look. Cheers :)  

As far as a RoadMap goes, the driving force behind this being "open sourced" was so AppVeyor CI could be more easily setup. It was decided that an internal .NET project which was using a javascript bridge and ripple-lib for signing would be better served by .NET code.

**Comment by moshejoshua** [comment]
Hi Guys,

FYI: RippleStream has most of the functionality included in ripple-lib,
replete with a transaction-object parser,and its object model already
strongly typed (in C#).  RippleStream has a direct call (via websocket
connection object) to send Json and receive .net objects via delegated
events representative of the returned rippled json structure. (also keep
in-mind that not all the returned rippled json structures are exactly
uniform, both in their structure as well as in naming conventions).

I don't know however what the IP issues would be in sharing that code,
since Ripple.NET project is open and RippleStream is not.

Any ideas of how to move forward on melding the two together?

On Mon, Dec 28, 2015 at 10:50 AM, sublimator <notifications@github.com>
wrote:

> create strongly-typed unsigned transaction objects etc
>
> Do you have any links? Would love to take a look. Cheers :)
>
> As far as a RoadMap goes, the driving force behind this being "open
> sourced" was so AppVeyor CI could be more easily setup. It was decided that
> an internal .NET project which was using a javascript bridge and ripple-lib
> for signing would be better served by .NET code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ripple/ripple-dot-net/issues/12#issuecomment-167591923>
> .
>



-- 

*Moshe Joshua*
Phone:  917-719-6656
Email:  moshejoshua@gmail.com <moshejoshua@gmail.com>

<https://www.facebook.com/moshejoshua.96>
<https://www.linkedin.com/pub/moshe-joshua/5/95/559>
<https://twitter.com/#!/moshejoshua>  <http://google.com/+MosheJoshua>

**Comment by matejr** [comment]
Yeah, it would be great if Ripple could open source at least some parts of existing .NET code. Ripple REST has been retired and now there is only one up-to-date API (RippleAPI) which cannot be easily used from other languages.

@sublimator, there are currently no links. I'll try to come up with something in the following days.

**Comment by moshejoshua** [comment]
As long as Ripple can provide some direction on how they want to utilize the existing RippleStream code, I can portion-out the functions for Ripple.NET's generic/open usage.

**Comment by matejr** [comment]
@moshejoshua, you are the author of RippleStream?

**Comment by moshejoshua** [comment]
yes

**Comment by matejr** [comment]
> Do you have any links?

@sublimator, I've just extracted some code from one of the private defunct projects: 

https://github.com/matejr/cli-wallet

I also found this project: https://github.com/chriswill/RippleRPC.Net . My implementation of RPC client is similar to this one (but far less complete). Pinging @chriswill

**Comment by sublimator** [comment]
> https://github.com/chriswill/RippleRPC.Net 
Cool, I can see vestiges of ripple-lib-java in it (as does ripple-dot-net )

> https://github.com/matejr/cli-wallet
Thanks :) Will discuss with the powers what the plans are for .NET support other than RippleStream.

**Comment by chriswill** [comment]
Hi guys, hope my repo was of some help for you.  Haven't worked on it (or Ripple) in some time... It's far from complete and may be now outdated.  I haven't tracked any API changes.

**Comment by sublimator** [comment]
Thanks Chris. I think there's some push towards using the new RippleAPI as "the" api for interacting with ripple. Maybe it makes sense to implement that in C#

**Comment by sublimator** [comment]
I checked with deciders and at the moment this is very low priority so I don't see much happening here in the future beyond bug-fixes.

**Comment by chriswill** [comment]
Is the Ripple Rest API the new api that you think should be supported in c#?  https://ripple.com/build/ripple-rest/

**Comment by sublimator** [comment]
ripple-rest is now deprecated (sorry) and has evolved into RippleAPI which
is a library rather than server. Currently there is only JS support. I
don't think ripple wants to put much in the way of resources into this at
present beyond basic signing support.
