### ISSUE TITLE
Typed Transactions

### ISSUE THREAD

**Issue by sublimator** [ripple/ripple-dot-net#15]

**Comment by matejr** [comment]
Strongly typed transaction objects? Just for unsigned transactions or also for transactions in the ledger (with metadata)?

**Comment by sublimator** [comment]
@matejr 

Thoughts ?

**Comment by matejr** [comment]
> I would like to hear your thoughts about typed transactions. I saw you used interfaces, and UnsignedX

My use case was a little bit different than yours. The purpose of these interfaces was to support the fluent transaction builder (never fully implemented):

```C#
	var builder = new TransactionBuilder("sSECRET", feeProvider, pathProvider, 
                                         ledgerSequenceNumberProvider, sequenceNumberProvider, 
                                         reliableTransactionSubmitter);
	
	var r = builder.NewPaymentTransaction() // returns IUnsignedPaymentTransaction
	               .From("rACCOUNT")		// returns IUnsignedPaymentTransaction
				   .To("rACCOUNT")
				   .WithDestinationTag(100)
				   .WithAmount(10000.Xrp())
				   .WithPath(Path.Any)
				   .WithAutofilledFields(Fields.All)
				   .Sign() // returns IReliablySubmittableTransaction
				   .SubmitReliably();
```

You don't have to implement interfaces. However, if you create interface for each transaction type (and also provide default implementation), the life of developers will be easier because they can only add this interface to their already existing classes.

If you plan to fully replicate functionality of RippleAPI, then you should probably model transaction classes after RippleAPI ([this spec](https://ripple.com/build/rippleapi/#payment)). If not, then you should probably model them after format, expected by rippled ([this spec](https://ripple.com/build/transactions/#payment)).

These strongly typed classes don't need to cover every possible transaction. Just most common ones. For example, maybe you don't need to fully support paths.

IMHO you only need to create classes for new transactions that will be _submitted_ to rippled. There's no need to implement transaction class that also includes metadata etc.

**Comment by sublimator** [comment]
Thanks Matej, will ponder :)

**Comment by sublimator** [comment]
See #12
